Optimize imports
booksaw/BetterTeams pull request #637
Opened 2024-07-23 04:22 UTC by svaningelgem

Thanks a lot @booksaw for your fixes!

I added a (lot more) issues my IDE noticed. Each commit is 1 particular issue.
Mostly harmless.

Everything compiles fine 😀

2024-07-30 20:09 UTC, booksaw requested changes
Thanks for taking a look, most problems I have noticed so far are related to indentation. 

Just as a word of warning, I am very hesitant to PRs that have these many minor changes in as in the past it has caused problems that took several months of bug reports to clean up where unintentionally behaviour has been changed. (Mainly because BetterTeams has no automated testing and with a diff this large, I can't reasonably manually test every change)

2024-07-30 20:09 UTC, booksaw commented on src/main/java/com/booksaw/betterTeams/integrations/placeholder/TeamPlaceholderOptionsEnum.java
> +    TeamPlaceholderOptionsEnum(IndividualTeamPlaceholderProvider teamProvider) {
Indentation :)

2024-07-30 20:11 UTC, booksaw commented
By the way, thanks for separating changes into different commits, it makes it a lot easier to review :)

2024-07-31 01:03 UTC, svaningelgem commented on src/main/java/com/booksaw/betterTeams/commands/team/DisbandCommand.java
> +			confirmation.remove(null);
In this case, I kept the original code:
```
		UUID found = null;
		// if they have already had the confirm dialogue

		// can use secret command /team disband confirm to validate disband success
		if (args.length > 1 && args[0].equals("confirm")) {
			team.disband();
			confirmation.remove(found);
			return new CommandResponse(true, "disband.success");
		}
```

As `found` is always `null` when you use 'confirm', I adjusted it to highlight that fact.
I've changed the code now. Could you verify if it has the same behaviour?

2024-07-31 01:14 UTC, svaningelgem commented on src/main/java/com/booksaw/betterTeams/commands/teama/TeleportTeama.java
> +    @Override
It seems you are using tabs instead of spaces. Hence the difference in indents.

2024-07-31 01:19 UTC, svaningelgem commented on src/main/java/com/booksaw/betterTeams/database/api/Database.java
> +        for (String placeholder : placeholders) {
tab/space differences again

2024-07-31 01:25 UTC, svaningelgem commented
> Just as a word of warning, I am very hesitant to PRs that have these many minor changes.
I completely understand. Problem is once I started with the code validation in my IDE, I just kept adding stuff.
Luckily the commit-by-commit approach seems to improve that a bit for you.

Normally in this PR there are no real changes. Just cleanup of your excellent codebase based on IntelliJ's comments about it.

2024-09-25 04:17 UTC, svaningelgem commented
Hi @booksaw , any chance you got lately to continue your review of this PR?

Thanks!

2025-01-19 09:21 UTC, closed without merging